quarkus.application.name=coffee-menu
quarkus.http.port=8080
app.version=${APP_VERSION:v1}
quarkus.otel.exporter.otlp.endpoint=${OTEL_ENDPOINT:http://otel-collector.tracing-system.svc.cluster.local:4317}
%dev.quarkus.log.console.json.enabled=false
%dev.quarkus.otel.sdk.disabled=true
