quarkus.application.name=frontend
quarkus.http.port=8080

quarkus.rest-client.rag.url=${RAG_URL:http://rag-service:8080}
quarkus.rest-client.rag.read-timeout=180000
quarkus.rest-client.orders.url=${ORDERS_URL:http://orders-service:8080}
quarkus.rest-client.projection.url=${PROJECTION_URL:http://projection-service:8080}

quarkus.otel.exporter.otlp.endpoint=${OTEL_ENDPOINT:http://otel-collector.tracing-system.svc.cluster.local:4317}
%dev.quarkus.log.console.json.enabled=false
%dev.quarkus.otel.sdk.disabled=true
