apiVersion: v1
kind: Service
metadata:
  name: projection-service
  labels:
    app: projection-service
    backstage.io/kubernetes-id: projection-service
    app.kubernetes.io/part-of: ai-demo
spec:
  selector:
    app: projection-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: projection-service
  labels:
    app: projection-service
    version: v1
    app.kubernetes.io/part-of: ai-demo
    backstage.io/kubernetes-id: projection-service
    app.openshift.io/runtime: quarkus
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"projection-service:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"app\")].image"}]'
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"mongodb"}]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projection-service
      version: v1
  template:
    metadata:
      labels:
        app: projection-service
        version: v1
        backstage.io/kubernetes-id: projection-service
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: /q/metrics
        proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}'
    spec:
      serviceAccountName: projection-service
      containers:
      - name: app
        image: projection-service:latest
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: OTEL_ENDPOINT
          value: http://otel-collector.tracing-system.svc.cluster.local:4317
        - name: KAFKA_BOOTSTRAP
          value: platform-kafka-bootstrap.kafka.svc.cluster.local:9092
        - name: MONGODB_URL
          value: mongodb://mongodb:27017
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: '1'
            memory: 768Mi
